language: java
jdk:
 - oraclejdk8
deploy:
  provider: elasticbeanstalk
  access_key_id: AKIAIJNJDQOK7C6CASOQ
  secret_access_key:
    secure: "I958PD0+8B0KE17HLQJBJTNgyAyli0zA0q4w+1g1AEgy5/Pdo0t3ZqrVlc6LZsZ+KYKLIrFzupVTQdqXnHwQYXgSJ4c6Yz+qWyWL7PVJlZSCTN9axif+BjBLVf2s4ZqXqXF2NVSeGaV8TylbrDa0ty/4rQ4COlzQh94B5wGpYWHJXF+w6R+ZSdDaBn9a+Qnq1Uk/80wflSZVpqXcbBUuGsJthjGGl4NYo1Nt0q/wMIO9AXosz12KepFZLNZU6AXxzESct9c/7mu+/+eJdTZgEey1t8ykQRb9/rCqSolnXU1z9VEeTqf+XU+A4hgqZcsCqtS027MmZZHuUcZyopQ8pp5z++XMOi3+5maxVopWGmlPX08x+CVz7KOS6o5D2fnAo7ytFb9F7UFuVmHXw0On7vhXVuRfipTrio+DiyfWNAMXjCwemTcJqN5gI3AIukIfdDDdZFIANv3fw4A8I8b1hstwG5YV9XIclQp7F3bcpoKz2saoY+YcE8Fh9R+scTR7kUs5UEb6AsRBw0vACjlyEalftnSWOjyBhb4u4z4k3UoSNpX0I/O8hC/n8XlA9f2O+8lbaSHo+I9Ik9mRLp0wh+uXErN2KZ8pthTTDgHyWlMHdL8WXmEkM4mQLLdgvY1sRfgNuBJN2Ko+9xhUTFffv+SldHUooHelE0CEaVxdRVU="
  region: "us-east-1"
  app: "poli-booking"
  env: "DEV-polibooking"
  bucket_name: "elasticbeanstalk-us-east-1-804492321058"
  skip_cleanup: true
  zip_file: 'target/servicios-al-estudiante-0.0.1-SNAPSHOT.jar'
before_install:
  - npm install -g bower
  - bower install
after_success:
  - mvn jacoco:report coveralls:report